EXPERIMENT:
  NAME: ""
  TAG: "DKD,vgg13,wrn_16_2"
  PROJECT: "vgg13"
DISTILLER:
  TYPE: "DKD"
  TEACHER: "vgg13"
  STUDENT: "wrn_16_2"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
IAKD:
  SHAPES: [1,8,16,32]
  OUT_SHAPES: [1,4,8,16]
  IN_CHANNELS: [64,128,256,256]
  OUT_CHANNELS: [128,256,512,512]