EXPERIMENT:
  NAME: ""
  TAG: "dkd,wrn_40_2,wrn_40_1"
  PROJECT: "clip_dkd"
DISTILLER:
  TYPE: "DKD_clip"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_40_1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 6.0
