EXPERIMENT:
  NAME: ""
  TAG: "CTKD,res32x4,vgg8"
  PROJECT: "CTKD"
DISTILLER:
  TYPE: "CTKD"
  TEACHER: "resnet32x4"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
