EXPERIMENT:
  NAME: ""
  TAG: "iakd,res32x4,res32"
  PROJECT: "IAKD"
DISTILLER:
  TYPE: "IAKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
IAKD:
  OUT_SHAPES: [1,8,16,32]
  SHAPES: [1,4,8,16]
  OUT_CHANNELS: [64,128,256,256]
  IN_CHANNELS: [16,32,64,64]
