EXPERIMENT:
  NAME: ""
  TAG: "iakd,res50,res20"
  PROJECT: "IAKD"
DISTILLER:
  TYPE: "IAKD"
  TEACHER: "ResNet50"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
IAKD:
  SHAPES: [1,4,8,16]
  OUT_SHAPES: [1,8,16,32]
  IN_CHANNELS: [16,32,64,64]
  OUT_CHANNELS: [256,512,1024,2048,2048]
