EXPERIMENT:
  NAME: ""
  TAG: "kd_N,res32x4,res8x4_v12"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KD_"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
KD_:
  A: 1
  B: 1
  C: 1.2

