EXPERIMENT:
  NAME: ""
  TAG: "dkd,res32x4,wrn_40_2,vgg8"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "DKD_M"
  TEACHER: "wrn_40_2"
  TEACHER2: "wrn_40_2"
  STUDENT: "wrn_16_2"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 6.0
