EXPERIMENT:
  NAME: ""
  TAG: "KD_clip,vgg13,vgg8,of"
  PROJECT: "SOF"
DISTILLER:
  TYPE: "KD_clip"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
