EXPERIMENT:
  NAME: ""
  TAG: "tiny,vgg13"
  PROJECT: "tiny"
DISTILLER:
  TYPE: "NONE"
  TEACHER: "vgg13"
  STUDENT: "vgg13"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.1
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DATASET:
  TYPE: "tiny-imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
