EXPERIMENT:
  NAME: ""
  TAG: "vgg13_vgg8[7,12]"
  PROJECT: "T"
DISTILLER:
  TYPE: "KD_"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
KD_:
  A: 4
  B: 2
  C: 1.0
  T_MAX: 12.0
  T_MIN: 7.0

