EXPERIMENT:
  NAME: ""
  TAG: "wsl,res32x4,res32"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "WSL"
  TEACHER: "resnet32x4"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

